[package]
name = "atsi"
version = "0.0.7"
edition = "2021"

[dependencies]
clap = "3.1.15"
ctrlc = "3.2.2"
derive-getters = "0.2.0"
dirs = "4.0.0"
flate2 = "1.0.23"
futures = "0.3.21"
haikunator = "0.1.2"
log = "0.4.17"
nix = "0.24.1"
pretty_env_logger = "0.4.0"
prettytable-rs = "0.8.0"
reqwest = "0.11.10"
rlimit = "0.8.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.80"
tar = "0.4.38"
tokio = { version = "1.16.1", features = [ "full" ] }
yaml-rust = "0.4.5"
